# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Lingna Xu
baseurl: "" # Leave this empty
url: "" # Will use GitHub Pages domain

# Header Navigation
header_links:
  - title: "Home"
    url: "/" # Redirects to the root of the website
  - title: "About"
    url: "#about"
  - title: "Publications"
    url: "#publications"
  - title: "CV"
    url: "/cv.html" # Separate page
  - title: "Teaching"
    url: "#teaching"
  - title: "Resources"
    url: "#resources"

# Sidebar Information
sidebar:
  picture: "assets/images/profile.jpg" # Update with the actual image path
  name: "Lingna Xu"
  university: "Utah State University"
  location:
    text: "Logan, UT, USA"
    icon: "assets/icons/location.png" # Map pin icon
  email:
    text: "lingna.xu@usu.edu"
    icon: "assets/icons/email.png" # Envelope icon
  links:
    - label: "Google Scholar"
      url: "https://scholar.google.com/citations?user=0d1AY2cAAAAJ&hl=en"
      icon: "assets/icons/google-scholar.png" # Google Scholar icon
    - label: "LinkedIn"
      url: "https://www.linkedin.com/in/lingna-xu-045a43214/"
      icon: "assets/icons/linkedin.png" # LinkedIn icon

# Favicon and Icon
favicon: "🎲"

# Content Sections
sections:
  about:
    title: "About"
    content: "I am a first-year PhD student at [Utah State University](https://www.usu.edu), exploring computational thinking and instructional technology. This section will detail my academic background and research interests."

  publications:
    title: "Publications"
    content: "Currently, I have no publications, but I will update this section as I progress through my PhD journey."

  teaching:
    title: "Teaching"
    content: "I am currently a teaching assistant for ITLS 2500. I will add more details about my teaching experiences here."

  resources:
    title: "Resources"
    content: "This section will feature useful resources related to instructional technology, computational thinking, and learning sciences."

# Additional configurations can go below
...



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
